name: Format
on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          clangformat: 16.0.6
      - name: Format
        run: git clang-format && clang-format --version
